name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519_chena
          chmod 600 ~/.ssh/id_ed25519_chena
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts
        shell: bash

      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -i ~/.ssh/id_ed25519_chena -o StrictHostKeyChecking=no alumno@137.184.127.11 \
            "cd ~/lemp-sites/chena_martin/javascript && git pull origin main"
